[tool.poetry]
name = "doc_analyzer_2.1"
version = "0.1.0"
description = ""
authors = ["Seu Nome <seuemail@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"